import streamlit as st

st.caption("향후 업데이트 예정사항 입니다.")
st.caption("- 개선사항3. 분봉자료 얻기")
st.caption("- 개선사항4. 최적 퍼센트 추천")
st.caption("- 개선사항5. 직접 업로드 기능")
st.caption("- 개선사항8. 비청산 상황도 가정가능하도록")
st.caption("- 개선사항10. 인풋데이터를 리스트나 딕트로 만들어놔야해 ")
st.caption("- 개선사항11. 표에서 단위표시 화폐단위나 %형태로 ")
st.caption("- 개선사항11. 1회차 매도시 %상승할 때 매수 할 수 있도록 조건부여 ")
st.caption("- 개선사항11. 한국어패치 ")
st.caption("- 개선사항11. portfolio visualizer 완전모방구현 ")
st.caption("- 개선사항11. 지수수익률과 비교기능 ")
st.caption("- 개선사항11. 레코드별 (날짜별) 전략 수익률 확인기능 ")
st.caption("- 개선사항11. Effective Frontier 확인 기능 ")
st.caption("- 개선사항11. VaR 포함 리스크매니징 확인 기능 ")
st.caption("- 개선사항11. 최적 비율 추천 기능 Ex. 1회차 비율 // 회차별 U&,D& // 종목별 비율 ")
st.caption("- 개선사항11. 한 개 종목 조회화면은 훨씬 더 자세하게 할 수 있도록 ")
st.caption("- 개선사항11. 훨씬 더 적극적으로 참여할 수 있는 인터랙티브 인터페이스 ")
